-- MySQL Script generated by MySQL Workbench
-- 08/19/15 00:51:35
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema oeis
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `sequence`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sequence` (
  `id` INT UNSIGNED NOT NULL,
  `name` VARCHAR(512) NOT NULL,
  `eois_id` VARCHAR(10) NULL,
  `hois_id` VARCHAR(10) NULL,
  `offset_a` INT NOT NULL,
  `offset_b` INT NOT NULL,
  `imported_at` DATETIME NOT NULL,
  `updated_at` DATETIME NULL,
  `worker` TINYINT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

CREATE INDEX `updated_idx` ON `sequence` (`updated_at` ASC);

CREATE INDEX `eois_idx` ON `sequence` (`eois_id` ASC);

CREATE INDEX `hois_idx` ON `sequence` (`hois_id` ASC);

CREATE INDEX `offset_idx` ON `sequence` (`offset_a` ASC, `offset_b` ASC);

CREATE INDEX `worker_idx` ON `sequence` (`worker` ASC);


-- -----------------------------------------------------
-- Table `person`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `person` (
  `id` VARCHAR(100) NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `person_sequence`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `person_sequence` (
  `person` VARCHAR(100) NOT NULL,
  `sequence` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`person`, `sequence`),
  CONSTRAINT `person_sequence_sequence_fk`
    FOREIGN KEY (`sequence`)
    REFERENCES `sequence` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `person_sequence_person_fk`
    FOREIGN KEY (`person`)
    REFERENCES `person` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `sequence_idx` ON `person_sequence` (`sequence` ASC);


-- -----------------------------------------------------
-- Table `crossreference`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `crossreference` (
  `from_sequence` INT UNSIGNED NOT NULL,
  `to_sequence` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`from_sequence`, `to_sequence`),
  CONSTRAINT `crossreference_from_fk`
    FOREIGN KEY (`from_sequence`)
    REFERENCES `sequence` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sequence_keyword`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sequence_keyword` (
  `sequence` INT UNSIGNED NOT NULL,
  `keyword` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`sequence`, `keyword`),
  CONSTRAINT `sequence_keyword_sequence_fk`
    FOREIGN KEY (`sequence`)
    REFERENCES `sequence` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `keyword_idx` ON `sequence_keyword` (`keyword` ASC);


-- -----------------------------------------------------
-- Table `sequence_blob`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sequence_blob` (
  `sequence` INT UNSIGNED NOT NULL,
  `name` VARCHAR(512) NOT NULL,
  `beginning` TEXT NOT NULL,
  `fulltext` MEDIUMTEXT NOT NULL,
  PRIMARY KEY (`sequence`),
  CONSTRAINT `sequence_blob_sequence_fk`
    FOREIGN KEY (`sequence`)
    REFERENCES `sequence` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE FULLTEXT INDEX `name_idx` ON `sequence_blob` (`name` ASC);

CREATE FULLTEXT INDEX `beginning_idx` ON `sequence_blob` (`beginning` ASC);

CREATE FULLTEXT INDEX `fulltext_idx` ON `sequence_blob` (`fulltext` ASC);


-- -----------------------------------------------------
-- Table `mention`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mention` (
  `sequence` INT UNSIGNED NOT NULL,
  `mentions` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`sequence`, `mentions`),
  CONSTRAINT `mention_sequence_fk`
    FOREIGN KEY (`sequence`)
    REFERENCES `sequence` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
